# Activity 2 - Advanced data manipulation with Pandas

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwvLrbPL8nwN0ZpL83yhgn1-6P7xHf8D03Dk3qWRdwDQ&s)

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool.

Here, you will learn how to read data, describe, select features from a dataset, compute statistics, etc.

In [1]:
# Usual import
import pandas as pd

## Working with missing values

Missing values occur when no data value is stored for the variable in an observation.
In general, missing data can occur because of nonresponse, i.e. when no information is provided for one or more items.

It is common in data analysis and can have a significant effect on the conclusions that can be drawn from the data.

So it is important to take care about the missing before performing an analysis.

There are mostly two way to handle missing values:
1. delete the rows or the columns that contains many missing values
2. impute the missing values using the closest observations in the dataset

Usually, missing values are encoded as `NaN` (Not a Number) in Pandas

In [2]:
# Let's have an example

employees = pd.read_csv("data/employees.csv")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [4]:
# A new dataframe with True is the cell is missing
employees.isnull().sum()

# Or True is the cell is NOT missing
# employees.notnull()

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

In [5]:
print("data shape:", employees.shape)

# Remove rows which contain at least one missing value
employees = employees.dropna(axis=0, how="any")
print("data shape:", employees.shape)

# Remove rows which contain only missing values
employees = employees.dropna(axis=0, how="all")
print("data shape:", employees.shape)

data shape: (1000, 8)
data shape: (764, 8)
data shape: (764, 8)

0                 Marketing
1                   Unknown
2                   Finance
3                   Finance
4           Client Services
               ...
995            Distribution
996                 Finance
997                 Product
998    Business Development
999                   Sales
Name: Team, Length: 1000, dtype: object

In [12]:
employees["Team"] = employees["Team"].fillna("Unknown")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Unknown
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [7]:
employees = pd.read_csv("data/employees.csv")


# Missing values imputation
# Is it the best solution?
employees.fillna(0)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,0
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,0,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
# Impute the missing values with the last valid observation forward to next valid
# Is it the best solution?
employees.fillna(method="ffill")

In [ ]:
# Impute on one column and store the result in the data frame
employees["Team"] = employees.Team.fillna("Unknown")
employees

**Good practices for missing values imputation**

1. Answer the questions: Do you need to impute the missing values? Do you need to impute the missing values for all the columns?
2. Count the number of missing values per columns. If the number of rows that contains missing values if low, you can juste delete it.
3. Impute the missing values columns by columns because the method used may depend on the type of the column (numerical or categories)

## Working with duplicates

In some cases, the dataset contains exactly identical rows, i.e. duplicates. In a statistical point of view, the results can be biased due to possibly many duplicates.
It is of importance to identify the duplcated rows and to remove these rows.

In [19]:
# Toy example
data = {
    "Names": ["Bob", "Jessica", "Mary", "John", "Mel", "Bob"],
    "Births": [968, 155, 578, 403, 199, 968]
}
df = pd.DataFrame(data=data)
print(df)

# Drop the duplicates and display the resulted dataframe
df.drop_duplicates(["Names"])

     Names  Births
0      Bob     968
1  Jessica     155
2     Mary     578
3     John     403
4      Mel     199
5      Bob     968

     Names  Births
0      Bob     968
1  Jessica     155
2     Mary     578
3     John     403
4      Mel     199

In [16]:
df.groupby("Names").Births.aggregate(["sum", "mean", "median"])

          sum   mean  median
Names
Bob      1936  968.0   968.0
Jessica   155  155.0   155.0
John      403  403.0   403.0
Mary      578  578.0   578.0
Mel       199  199.0   199.0

In [ ]:
# What if there are pseudo-duplicates, i.e. not exact duplicates
data = {
    "Names": ["Bob", "Jessica", "Mary", "John", "Mel", "bob"],
    "Births": [968, 155, 578, 403, 199, 968]
}
df = pd.DataFrame(data=data)
print(df)

# Try to drop the duplicates and display the resulted dataframe
df.drop_duplicates()

**What about duplicated columns?**

Having duplicated columns can rarely occur but it can have a negative effect on your conclusions, for instance if your goal if to identify the most relevant features of your dataset.
So it is important to identify and to understand why they contain the same values. In general, the duplicated columns are simply removed.

## Advanced data selection

Advanced data manipulation involves more sophisticated techniques for selecting, filtering, and transforming data.

In [27]:
import pandas as pd

# Create a sample DataFrame
data = {
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8398748, 3980405, 2716000, 2328066],
    "Area": [468.9, 1213.9, 227.3, 637.5],
    "Median_Income": [55350, 60563, 51039, 49882]
}

cities_df = pd.DataFrame(data)

In [21]:
# Conditional selection

# Select cities with a population greater than 3 million.
selected_rows = cities_df[cities_df["Population"] > 3000000]
print(selected_rows)

          City  Population    Area  Median_Income
0     New York     8398748   468.9          55350
1  Los Angeles     3980405  1213.9          60563

In [24]:
# Multiple conditions

# Select cities with a population greater than 2 million and a median income less than $55,000.
selected_conditions = cities_df[
    (cities_df["Population"] > 2000000) 
    & (cities_df["Median_Income"] < 55000)
]
print(selected_conditions)

      City  Population   Area  Median_Income
2  Chicago     2716000  227.3          51039
3  Houston     2328066  637.5          49882

In [25]:
# Conditional selection for categorical columns using String method

# Select cities with names starting with "L".
selected_startswith_L = cities_df[cities_df["City"].str.startswith("L")]
print(selected_startswith_L)

          City  Population    Area  Median_Income
1  Los Angeles     3980405  1213.9          60563

In [34]:
# Conditional selection for categorical columns using isin() method

# Example 1: select cities from a predefined list
selected_cities = cities_df[cities_df["City"].isin(["New York", "Los Angeles"])]
print(selected_cities)


# Example 2: select rows based on multiple conditions using the `isin()` method with a data frame.

# First create a list of dictionaries for conditions
conditions = [
    {"City": "New York", "Population": 8398748},
    {"City": "Chicago", "Median_Income": 51039}
]

# Select rows that match any condition
selected_conditions_df = cities_df[cities_df.isin(conditions).all(axis=1)]
print(selected_conditions_df)

          City  Population    Area  Median_Income
0     New York     8398748   468.9          55350
1  Los Angeles     3980405  1213.9          60563
Empty DataFrame
Columns: [City, Population, Area, Median_Income]
Index: []

In [41]:
# Conditional selection using a custom function

# Example : Select cities based on a custom filtering function.
def custom_filter(row):
    return row["Area"] > 300 and row["Median_Income"] > 50000

# Apply the custom function using apply()
# The argument axis specifies the axis along which the function is applied (0 for rows and 1 for columns)
selected_custom_filter = cities_df[cities_df.apply(custom_filter, axis=1)]
print(selected_custom_filter)

          City  Population    Area  Median_Income
0     New York     8398748   468.9          55350
1  Los Angeles     3980405  1213.9          60563

In [ ]:
# Exercise: apply the previous methods to weather dataset and employees dataset

# Examples
# 1. Compute the average of precipitations for each month
# 2. Select the days in which there is snow

# TO DO

In [45]:
df_weather = pd.read_csv("data/weather.csv", sep=";")

In [49]:
df_weather.month.unique()

array(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype=object)

In [50]:
for month in df_weather.month.unique():
    
    avg_precipitation = df_weather[df_weather.month == month].precipitation.mean()
    print(f"The average precipitation in {month} is : {avg_precipitation:.1f}")

The average precipitation in January is : 3.8
The average precipitation in February is : 3.7
The average precipitation in March is : 4.9
The average precipitation in April is : 3.1
The average precipitation in May is : 1.7
The average precipitation in June is : 1.1
The average precipitation in July is : 0.4
The average precipitation in August is : 1.3
The average precipitation in September is : 2.0
The average precipitation in October is : 4.1
The average precipitation in November is : 5.4
The average precipitation in December is : 5.0

In [48]:
df_weather[df_weather.weather == "snow"]

           date  precipitation  temp_max  temp_min  wind weather     month
13   2012-01-14            4.1       4.4       0.6   5.3    snow   January
14   2012-01-15            5.3       1.1      -3.3   3.2    snow   January
15   2012-01-16            2.5       1.7      -2.8   5.0    snow   January
16   2012-01-17            8.1       3.3       0.0   5.6    snow   January
17   2012-01-18           19.8       0.0      -2.8   5.0    snow   January
18   2012-01-19           15.2      -1.1      -2.8   1.6    snow   January
19   2012-01-20           13.5       7.2      -1.1   2.3    snow   January
56   2012-02-26            1.3       5.0      -1.1   3.4    snow  February
58   2012-02-28            3.6       6.7      -0.6   4.2    snow  February
59   2012-02-29            0.8       5.0       1.1   7.0    snow  February
65   2012-03-06            0.5       6.7       0.0   2.7    snow     March
71   2012-03-12           19.3       8.3       0.6   6.2    snow     March
72   2012-03-13            9.4       5.6       0.6   5.3    snow     March
74   2012-03-15           23.9      11.1       5.6   5.8    snow     March
76   2012-03-17            9.4      10.0       0.6   3.8    snow     March
95   2012-04-05            4.6       9.4       2.8   1.8    snow     April
349  2012-12-15            5.3       4.4       0.6   5.1    snow  December
350  2012-12-16           22.6       6.7       3.3   5.5    snow  December
352  2012-12-18            3.3       3.9       0.6   5.3    snow  December
353  2012-12-19           13.7       8.3       1.7   5.8    snow  December
359  2012-12-25           13.5       5.6       2.8   4.2    snow  December
375  2013-01-10            0.3       3.3      -0.6   2.1    snow   January
445  2013-03-21            8.1      10.0       2.2   4.9    snow     March


## Grouping and combining data

Grouping data allows you to split the data into groups based on some criteria, and combining involves aggregating or summarizing the data within each group.

In [51]:
# Grouping data with the groupby() method

data = {"Category": ["A", "B", "A", "B", "A", "B"],
        "Value": [10, 15, 20, 25, 30, 35]}
df = pd.DataFrame(data)

# Group by the "Category" column
grouped = df.groupby("Category")

In [56]:
grouped['Value'].sum()

Category
A    60
B    75
Name: Value, dtype: int64

In [52]:
# Aggregating data within Groups

# Calculate the sum within each group
sum_per_category = grouped['Value'].sum()
print(sum_per_category)

# Calculate the mean within each group
mean_per_category = grouped['Value'].mean()
print(mean_per_category)

Category
A    60
B    75
Name: Value, dtype: int64
Category
A    20.0
B    25.0
Name: Value, dtype: float64

In [53]:
# Combining data with agg() method

# e.g. calculate both sum and mean for "Value" within each group
result_agg = grouped.agg({"Value": ["sum", "mean"]})
print(result_agg)

         Value
           sum  mean
Category
A           60  20.0
B           75  25.0

In [54]:
# Custom aggregation functions

# Define a custom aggregation function
def custom_agg(values):
    return values.max() - values.min()

# Apply the custom aggregation function within each group
custom_result = grouped.agg({"Value": custom_agg})
print(custom_result)

          Value
Category
A            20
B            20

In [ ]:
# Exercise: apply the previous methods to weather dataset and employees dataset

# TO DO

## Concatenating DataFrames

Concatenation is the operation of combining two or more data frames together.
Many concatenation methods exist depending on what you need as a result:
* Horizontal concatenation means stacking the rows of the data frames
* Vertical concatenation means combining the data frames along the columns

In [60]:
# 1/ Vertical concatenation

# Create two sample DataFrames
df1 = pd.DataFrame({"A": [1, 2], "C": [3, 4]})
df2 = pd.DataFrame({"A": [5, 6], "B": [7, 8]})

# Concatenate vertically (stack rows)
result_vertical = pd.concat([df1, df2], ignore_index=True)
print(result_vertical)

# Remark: the argument ignore_index=True is used to reset the index of the resulting DataFrame.

# 2/ Horizontal concatenation

# Concatenate horizontally (join columns), using the argument axis=1
result_horizontal = pd.concat([df1, df2], axis=1)
print(result_horizontal)

   A    C    B
0  1  3.0  NaN
1  2  4.0  NaN
2  5  NaN  7.0
3  6  NaN  8.0
   A  C  A  B
0  1  3  5  7
1  2  4  6  8

In [61]:
# Concatenating dataFrames with different columns

# Create two DataFrames with different columns
df1 = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df2 = pd.DataFrame({"C": [5, 6], "D": [7, 8]})

# Concatenate vertically with different columns
result_diff_columns = pd.concat([df1, df2], ignore_index=True)
print(result_diff_columns)

# Remark: In this case, Pandas fills in missing values with NaN for columns that don't exist in one of the data frames.

     A    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
2  NaN  NaN  5.0  7.0
3  NaN  NaN  6.0  8.0

In [62]:
# Concatenating data frames with matching columns:

# Create two DataFrames with matching columns
df1 = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df2 = pd.DataFrame({"A": [5, 6], "B": [7, 8]})

# Concatenate vertically with matching columns
result_match_columns = pd.concat([df1, df2], ignore_index=True)
print(result_match_columns)

# Remark: Here, both DataFrames have the same columns, so the concatenation works seamlessly.

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

## Reshaping and pivoting data

Reshaping and pivoting data involve transforming the structure of a data frame to better suit the analysis or visualization needs.

A pivot table allows to summarize, aggregate, and rearrange tabular data. This is convenient way to transform and organize the data according to their analysis needs.

Components of a pivot table:

- **Rows:** The rows of the pivot table typically represent categorical variables or groups based on which you want to aggregate the data

- **Columns:** The columns represent another set of categorical variables. The data is grouped and summarized based on the intersection of rows and columns

- **Values:** The values in the pivot table are the result of applying an aggregation function (e.g., sum, mean, count) to the numerical data in the original dataset.

A pivot table is also known as cross table and it is related to what we call wide format table.

In other hands, long format tables are the results of the "unpivot" operation: one or more columns are identifier variables (id_vars), while all other columns, considered measured variables (value_vars), are unpivoted to the row axis, leaving just two non-identifier columns, ‘variable’ and ‘value’.

The two main functions for reshaping data are `melt()` (from wide to long format) and `pivot_table()` (from long to wide format).

![](https://gitlabsu.sorbonne-universite.fr/scai/data-visualization/-/raw/main/assets/reshaping_examples.png)

**Pivot function**

In [ ]:
import pandas as pd

# load tha dataset
employees = pd.read_csv("https://gitlabsu.sorbonne-universite.fr/scai/data-visualization/-/raw/main/data/employees.csv").dropna(axis=0)
employees

# pivot
pivot = employees.pivot_table(index="Team", columns="Gender", values="Salary", aggfunc="mean")

# Display with rounding numbers
pivot.round()

**Melt Function**

The `melt()` function is used to unpivot or melt a data frame from wide format to long format. It is particularly useful when you have a data frame where columns represent different variables, and you want to transform it to a format where these variables are represented as rows.

In [ ]:
import pandas as pd
employees = pd.read_csv("https://gitlabsu.sorbonne-universite.fr/scai/data-visualization/-/raw/main/data/employees.csv").dropna(axis=0)

# melt
melt = pd.melt(employees, id_vars="First Name", var_name="Variable", value_name="Value")

In [ ]:
# Another example

# rows: observations, cols: features, cells: value for one observation and one feature
data = {
    "Date": ["2022-01-01", "2022-01-02", "2022-01-03"],
    "Temperature": [25, 28, 24],
    "Humidity": [50, 45, 60]
}

df = pd.DataFrame(data)
print(df)

# Long format. cols: ID, Variable, values
melt = pd.melt(df, id_vars=["Date"], var_name="Variable", value_name="Value")
print(melt)

# Wide format from the long format = the initial data
melt.pivot(index="Date", columns="Variable", values="Value")

## Working with time series

Time Series Analysis involves working with datasets where the data points are indexed by time, see the example below. Pandas provides a set of tools for handling and analyzing time series data:

* Convert the dates to a convinient format
* Resample the data: upsampling or downsampling.
* Rolling statistics
* Time-based slicing: selecting a range of data for a time interval

```yaml
      Date  Temperature  Humidity
2022-01-01           25        50
2022-01-02           28        45
2022-01-03           24        60
...                 ...       ...
```

In [76]:
# Toy dataset

import pandas as pd

data = {
    "date": ["2022-01-01", "2022-01-02", "2022-01-03"],
    "temperature": [25, 28, 24],
    "humidity": [50, 45, 60]
}

df = pd.DataFrame(data)
df

         date  temperature  humidity
0  2022-01-01           25        50
1  2022-01-02           28        45
2  2022-01-03           24        60

In [77]:
df.dtypes

date           object
temperature     int64
humidity        int64
dtype: object

**Converting to data frame and setting index**

This is to ensure that the time-related columns are in datetime format and set as the index. This allows for convenient time-based operations.

In [64]:
# Convert "Date" to datetime format
df["date"] = pd.to_datetime(df["date"])
df.dtypes

date           datetime64[ns]
temperature             int64
humidity                int64
dtype: object

In [75]:
df.dtypes

temperature    int64
humidity       int64
dtype: object

In [65]:
df

        date  temperature  humidity
0 2022-01-01           25        50
1 2022-01-02           28        45
2 2022-01-03           24        60

In [72]:
df["date"].dt.strftime("%m/%Y")

0    01/2022
1    01/2022
2    01/2022
Name: date, dtype: object

In [73]:
# The datetime object implements usefull methods, e.g. that extract the year, month, day, etc.
dt = df["date"]
year = dt.dt.year
month = dt.dt.month_name()
day = dt.dt.day_name()

# Print the results
print(year)
print(month)
print(day)

0    2022
1    2022
2    2022
Name: date, dtype: int32
0    January
1    January
2    January
Name: date, dtype: object
0    Saturday
1      Sunday
2      Monday
Name: date, dtype: object

In [74]:
# set the datetime object as the index
df.set_index("date", inplace=True) # inplace modify the data frame and does not return anything
df

            temperature  humidity
date
2022-01-01           25        50
2022-01-02           28        45
2022-01-03           24        60

**Resampling**

This involves changing the frequency of the time series data.
The function `resample()` is used to aggregate or downsample the data based on a specified frequency (e.g., daily to monthly).

In [ ]:
# Resample daily data to monthly and calculate the mean
df_resampled = df.resample("M").mean()

df_resampled

**Rolling Statistics:**

Rolling functions help in calculating rolling statistics like moving averages or rolling standard deviations.

In [ ]:
# Calculate a 3-day rolling mean
df["Rolling_Mean"] = df["temperature"].rolling(window=3).mean()
df

**Time-based Slicing**

Pandas allows you to slice and filter data based on time intervals.

In [ ]:
# Select data for a specific time range
df_subset = df["2022-01-01":"2022-01-02"]
df_subset

In [ ]:
# Exercise: apply the previous methods to weather dataset

# TO DO