# Activity 1 - Basic operations with Pandas

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwvLrbPL8nwN0ZpL83yhgn1-6P7xHf8D03Dk3qWRdwDQ&s)

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool.

Here, you will learn how to read data, describe, select features from a dataset, compute statistics, etc.

In [36]:
# Usual import
import pandas as pd

## Create a DataFrame object

In [2]:
# Option 1: from a list
data = [("Mary", 968),
        ("Jessica", 155),
        ("Bob", 578),
        ("John", 403),
        ("Mel", 199)]
columns = ["Names", "Births"]

df = pd.DataFrame(data=data, columns=columns)
df

     Names  Births
0     Mary     968
1  Jessica     155
2      Bob     578
3     John     403
4      Mel     199

In [3]:
# Option 2: from a dictionary
data = {
    "Names": ["Bob", "Jessica", "Mary", "John", "Mel"],
    "Births": [968, 155, 578, 403, 199]
}

df = pd.DataFrame(data=data)
df

     Names  Births
0      Bob     968
1  Jessica     155
2     Mary     578
3     John     403
4      Mel     199

Dataframes are **tabular data structures**: they contains rows and columns.

The rows and the columns of a dataframe **are both named**. Use the following instructions to get the lists of the row names and the column names:

```python
# Row names
df.index

# Column names
df.columns
```

By default, the names of the rows are numbers (0, 1, 2, ...) but it can be modified.

In [38]:
# prints the row and column names
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=5, step=1)
Index(['Names', 'Births'], dtype='object')

In [39]:
# Modify the row names
df.index = ["row0", "row1", "row2", "row3", "row4"]
print(df.index)

Index(['row0', 'row1', 'row2', 'row3', 'row4'], dtype='object')

In [40]:
# Modify the column names
df.columns = ["names", "births"]
print(df.columns)

Index(['names', 'births'], dtype='object')

In [41]:
# Prints the type of the columns
df.dtypes

names     object
births     int64
dtype: object

In [42]:
# Prints the dimensions of the data frame
df.shape

(5, 2)

## Add columns to a data frame

Adding a new column to an existing data frame is done as follows:

```python
df[new_col_name] = some_values
```

if `new_col_name` is the name of the new column and `some_values` is a sequence of the values we want to store in the data frame.

In [43]:
new_col_name = "Number"
values = [10, 11, 12, 13, 14]
df[new_col_name] = values
df

        names  births  Number
row0      Bob     968      10
row1  Jessica     155      11
row2     Mary     578      12
row3     John     403      13
row4      Mel     199      14

In [44]:
df["test_col"] = ["test"]*5
df

        names  births  Number test_col
row0      Bob     968      10     test
row1  Jessica     155      11     test
row2     Mary     578      12     test
row3     John     403      13     test
row4      Mel     199      14     test

In [50]:
df[(df["births"] >= 400)&(df["Number"] < 11)]

     names  births  Number test_col
row0   Bob     968      10     test

## Select a column

When selecting a column from a dataframe, the output is a ```Series``` object.

It can be done in two ways:

In [10]:
# Option 1
df.births

row0    968
row1    155
row2    578
row3    403
row4    199
Name: births, dtype: int64

In [11]:
# Option 2
df["births"]

row0    968
row1    155
row2    578
row3    403
row4    199
Name: births, dtype: int64

## Select columns and rows

Selecting both rows and columns is possible knowing the name of the rows and the name of the columns and using the attribute `.loc`:

```python
df.loc[row_names, col_names]
```

where `row_names` is the list of the names of the rows and `col_names` the names of the columns.

In [12]:
data = {
    "Names": ["Bob", "Jessica", "Mary", "John", "Mel"],
    "Births": [968, 155, 578, 403, 199]
}

df = pd.DataFrame(data=data)

In [13]:
row_names = [0, 2, 4]
col_names = ["Births"]
df.loc[row_names, col_names]

   Births
0     968
2     578
4     199

In [14]:
# Or select multiple columns
row_names = [0, 2, 4]
col_names = ["Births", "Names"]
df.loc[row_names, col_names]

   Births Names
0     968   Bob
2     578  Mary
4     199   Mel

In [15]:
# Alternativelly
# the character ':' means selecting all the rows of the dataframe
df.loc[:, "Births"]

0    968
1    155
2    578
3    403
4    199
Name: Births, dtype: int64

## Read an external file (CSV, XLS)

When working on data, the first question we have in mind is how to import the dataset in Python.

There are many functions for importing datasets, depending on its format (CSV, Excel, JSON, SQL, etc.). The two main functions when working on tabular datasets are:
* `pd.read_csv`: the input file is a simple text file whose values are separated by a comma or a semi-colon. CSV means "comma separated values".
* `pd.read_excel`: can import an Excel sheet

In [16]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool | lib.NoDefault' = <no_default>,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    infer_datetime_format: 'bool | lib.NoDefault' = <no_default>,
    keep_date_col: 'bool | lib.NoDefault' = <no_default>,
    date_parser: 'Callable | lib.NoDefault' = <no_default>,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    delim_whitespace: 'bool | lib.NoDefault' = <no_default>,
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Character or regex pattern to treat as the delimiter. If ``sep=None``, the
    C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator from only the first valid
    row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
    In addition, separators longer than 1 character and different from
    ``'\s+'`` will be interpreted as regular expressions and will also force
    the use of the Python parsing engine. Note that regex delimiters are prone
    to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, optional
    Alias for ``sep``.
header : int, Sequence of int, 'infer' or None, default 'infer'
    Row number(s) containing column labels and marking the start of the
    data (zero-indexed). Default behavior is to infer the column names: if no ``names``
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly to ``names`` then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a :class:`~pandas.MultiIndex` on the columns
    e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : Sequence of Hashable, optional
    Sequence of column labels to apply. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : Hashable, Sequence of Hashable or False, optional
  Column(s) to use as row label(s), denoted either by column labels or column
  indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
  will be formed for the row labels.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g., when you have a malformed file with delimiters at
  the end of each line.
usecols : Sequence of Hashable or Callable, optional
    Subset of columns to select, denoted either by column labels or column indices.
    If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in ``names`` or
    inferred from the document header row(s). If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
    preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
    for columns in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to ``True``. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : dtype or dict of {Hashable : dtype}, optional
    Data type(s) to apply to either the whole dataset or individual columns.
    E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
    Use ``str`` or ``object`` together with suitable ``na_values`` settings
    to preserve and not interpret ``dtype``.
    If ``converters`` are specified, they will be applied INSTEAD
    of ``dtype`` conversion.

    .. versionadded:: 1.5.0

        Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
        the default determines the ``dtype`` of the columns which are not explicitly
        listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster, while the python engine
    is currently more feature-complete. Multithreading is currently only supported by
    the pyarrow engine.

    .. versionadded:: 1.4.0

        The 'pyarrow' engine was added as an *experimental* engine, and some features
        are unsupported, or may not work correctly, with this engine.
converters : dict of {Hashable : Callable}, optional
    Functions for converting values in specified columns. Keys can either
    be column labels or column indices.
true_values : list, optional
    Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
false_values : list, optional
    Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : int, list of int or Callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (``int``)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
    Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
    per-column ``NA`` values.  By default the following values are interpreted as
    ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
    "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
    "n/a", "nan", "null ".

keep_default_na : bool, default True
    Whether or not to include the default ``NaN`` values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
      is appended to the default ``NaN`` values used for parsing.
    * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
      the default ``NaN`` values are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
      the ``NaN`` values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
      strings will be parsed as ``NaN``.

    Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of ``na_values``). In
    data without any ``NA`` values, passing ``na_filter=False`` can improve the
    performance of reading a large file.
verbose : bool, default False
    Indicate number of ``NA`` values placed in non-numeric columns.

    .. deprecated:: 2.2.0
skip_blank_lines : bool, default True
    If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
    The behavior is as follows:

    * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
      ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
    * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
      each as a separate date column.
    * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
      as a single date column. Values are joined with a space before parsing.
    * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
      result 'foo'. Values are joined with a space before parsing.

    If a column or index cannot be represented as an array of ``datetime``,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an ``object`` data type. For
    non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
    :func:`~pandas.read_csv`.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
    format of the ``datetime`` strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.

    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has no effect.

keep_date_col : bool, default False
    If ``True`` and ``parse_dates`` specifies combining multiple columns then
    keep the original columns.
date_parser : Callable, optional
    Function to use for converting a sequence of string columns to an array of
    ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. pandas will try to call ``date_parser`` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by ``parse_dates`` into a single array
    and pass that; and 3) call ``date_parser`` once for each row using one or
    more strings (corresponding to the columns defined by ``parse_dates``) as
    arguments.

    .. deprecated:: 2.0.0
       Use ``date_format`` instead, or read in as ``object`` and then apply
       :func:`~pandas.to_datetime` as-needed.
date_format : str or dict of column -> format, optional
    Format to use for parsing dates when used in conjunction with ``parse_dates``.
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
        time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
        and you should probably use it along with `dayfirst`.

    .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If ``True``, use a cache of unique, converted dates to apply the ``datetime``
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return ``TextFileReader`` object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Number of lines to read from the file per chunk. Passing a value will cause the
    function to return a ``TextFileReader`` object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    .. versionadded:: 1.5.0
        Added support for `.tar` files.

    .. versionchanged:: 1.4.0 Zstandard support.

thousands : str (length 1), optional
    Character acting as the thousands separator in numerical values.
decimal : str (length 1), default '.'
    Character to recognize as decimal point (e.g., use ',' for European data).
lineterminator : str (length 1), optional
    Character used to denote a line break. Only valid with C parser.
quotechar : str (length 1), optional
    Character used to denote the start and end of a quoted item. Quoted
    items can include the ``delimiter`` and it will be ignored.
quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
    ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
    characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
    or ``lineterminator``.
doublequote : bool, default True
   When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    Character used to escape other characters.
comment : str (length 1), optional
    Character indicating that the remainder of line should not be parsed.
    If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter ``header`` but not by
    ``skiprows``. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
    treated as the header.
encoding : str, optional, default 'utf-8'
    Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

encoding_errors : str, optional, default 'strict'
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    .. versionadded:: 1.3.0

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
    ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
    override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are :

    - ``'error'``, raise an Exception when a bad line is encountered.
    - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
    - ``'skip'``, skip bad lines without raising or warning when they are encountered.

    .. versionadded:: 1.3.0

    .. versionadded:: 1.4.0

        - Callable, function with signature
          ``(bad_line: list[str]) -> list[str] | None`` that will process a single
          bad line. ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new ``list`` of strings with more elements than
          expected, a ``ParserWarning`` will be emitted while dropping extra elements.
          Only supported when ``engine='python'``

    .. versionchanged:: 2.2.0

        - Callable, function with signature
          as described in `pyarrow documentation
          <https://arrow.apache.org/docs/python/generated/pyarrow.csv.ParseOptions.html
          #pyarrow.csv.ParseOptions.invalid_row_handler>`_ when ``engine='pyarrow'``

delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be

In [53]:
# Important: be careful of the separator ! By default, the values are separated by a comma but sometimes, we need to modified it.
weather = pd.read_csv("data/weather.csv")
weather

     date;precipitation;temp_max;temp_min;wind;weather;month
0           2012-01-01;0.0;12.8;5.0;4.7;drizzle;January
1             2012-01-02;10.9;10.6;2.8;4.5;rain;January
2              2012-01-03;0.8;11.7;7.2;2.3;rain;January
3             2012-01-04;20.3;12.2;5.6;4.7;rain;January
4               2012-01-05;1.3;8.9;2.8;6.1;rain;January
...                                                 ...
1456            2015-12-27;8.6;4.4;1.7;2.9;fog;December
1457            2015-12-28;1.5;5.0;1.7;1.3;fog;December
1458            2015-12-29;0.0;7.2;0.6;2.6;fog;December
1459           2015-12-30;0.0;5.6;-1.0;3.4;sun;December
1460           2015-12-31;0.0;5.6;-2.1;3.5;sun;December

[1461 rows x 1 columns]

In [57]:
# With the correct separator
weather = pd.read_csv("data/weather.csv", sep=";")
weather

            date  precipitation  temp_max  temp_min  wind  weather     month
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle   January
1     2012-01-02           10.9      10.6       2.8   4.5     rain   January
2     2012-01-03            0.8      11.7       7.2   2.3     rain   January
3     2012-01-04           20.3      12.2       5.6   4.7     rain   January
4     2012-01-05            1.3       8.9       2.8   6.1     rain   January
...          ...            ...       ...       ...   ...      ...       ...
1456  2015-12-27            8.6       4.4       1.7   2.9      fog  December
1457  2015-12-28            1.5       5.0       1.7   1.3      fog  December
1458  2015-12-29            0.0       7.2       0.6   2.6      fog  December
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun  December
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun  December

[1461 rows x 7 columns]

In [63]:
weather["temp_mean"] = (weather["temp_max"] + weather["temp_min"]) / 2
weather.head()

,date,precipitation,temp_max,temp_min,wind,weather,month,temp_mean
0,2012-01-01,0.0,12.8,5.0,4.7,drizzle,January,8.90
1,2012-01-02,10.9,10.6,2.8,4.5,rain,January,6.70
2,2012-01-03,0.8,11.7,7.2,2.3,rain,January,9.45
3,2012-01-04,20.3,12.2,5.6,4.7,rain,January,8.90
4,2012-01-05,1.3,8.9,2.8,6.1,rain,January,5.85

In [64]:
# prints the types of each column

# int64, int32, int: integrers
# float64, float32, float: floating-point numbers
# object: non-numerical type, e.g. strings

weather.dtypes

date              object
precipitation    float64
temp_max         float64
temp_min         float64
wind             float64
weather           object
month             object
temp_mean        float64
dtype: object

In [71]:
weather["month"].str.upper()

0        JANUARY
1        JANUARY
2        JANUARY
3        JANUARY
4        JANUARY
          ...
1456    DECEMBER
1457    DECEMBER
1458    DECEMBER
1459    DECEMBER
1460    DECEMBER
Name: month, Length: 1461, dtype: object

## Describe the data

Pandas offers a large amount of functions for data description

In [21]:
# prints a summary of the data
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   object
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
 6   month          1461 non-null   object
dtypes: float64(4), object(3)
memory usage: 80.0+ KB

In [72]:
# Statistics of each numerical column of the data
weather.describe()

       precipitation     temp_max     temp_min         wind    temp_mean
count    1461.000000  1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136    12.336927
std         6.680194     7.349758     5.023004     1.437825     5.998051
min         0.000000    -1.600000    -7.100000     0.400000    -3.800000
25%         0.000000    10.600000     4.400000     2.200000     7.750000
50%         0.000000    15.600000     8.300000     3.000000    11.950000
75%         2.800000    22.200000    12.200000     4.000000    17.200000
max        55.900000    35.600000    18.300000     9.500000    26.700000

In [23]:
# Prints the 5 first rows of the dataset
weather.head(5)

         date  precipitation  temp_max  temp_min  wind  weather    month
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle  January
1  2012-01-02           10.9      10.6       2.8   4.5     rain  January
2  2012-01-03            0.8      11.7       7.2   2.3     rain  January
3  2012-01-04           20.3      12.2       5.6   4.7     rain  January
4  2012-01-05            1.3       8.9       2.8   6.1     rain  January

In [24]:
# or the last rows
weather.tail()

            date  precipitation  temp_max  temp_min  wind weather     month
1456  2015-12-27            8.6       4.4       1.7   2.9     fog  December
1457  2015-12-28            1.5       5.0       1.7   1.3     fog  December
1458  2015-12-29            0.0       7.2       0.6   2.6     fog  December
1459  2015-12-30            0.0       5.6      -1.0   3.4     sun  December
1460  2015-12-31            0.0       5.6      -2.1   3.5     sun  December

In [25]:
# ADVANCED set new indexes with the values of one column, and store it
weather = weather.set_index("date")
weather.head()

            precipitation  temp_max  temp_min  wind  weather    month
date
2012-01-01            0.0      12.8       5.0   4.7  drizzle  January
2012-01-02           10.9      10.6       2.8   4.5     rain  January
2012-01-03            0.8      11.7       7.2   2.3     rain  January
2012-01-04           20.3      12.2       5.6   4.7     rain  January
2012-01-05            1.3       8.9       2.8   6.1     rain  January

## Statistics

Many statistics are provided by Pandas:
* descriptive statistics: mean, median, standard deviation, etc.
* methods for categorical data: values counting

In [26]:
# Describe again
weather.describe()

       precipitation     temp_max     temp_min         wind
count    1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136
std         6.680194     7.349758     5.023004     1.437825
min         0.000000    -1.600000    -7.100000     0.400000
25%         0.000000    10.600000     4.400000     2.200000
50%         0.000000    15.600000     8.300000     3.000000
75%         2.800000    22.200000    12.200000     4.000000
max        55.900000    35.600000    18.300000     9.500000

In [73]:
weather.head()

,date,precipitation,temp_max,temp_min,wind,weather,month,temp_mean
0,2012-01-01,0.0,12.8,5.0,4.7,drizzle,January,8.90
1,2012-01-02,10.9,10.6,2.8,4.5,rain,January,6.70
2,2012-01-03,0.8,11.7,7.2,2.3,rain,January,9.45
3,2012-01-04,20.3,12.2,5.6,4.7,rain,January,8.90
4,2012-01-05,1.3,8.9,2.8,6.1,rain,January,5.85

In [77]:
weather[["precipitation", "temp_max"]]

      precipitation  temp_max
0               0.0      12.8
1              10.9      10.6
2               0.8      11.7
3              20.3      12.2
4               1.3       8.9
...             ...       ...
1456            8.6       4.4
1457            1.5       5.0
1458            0.0       7.2
1459            0.0       5.6
1460            0.0       5.6

[1461 rows x 2 columns]

In [74]:
# Compute the mean of each numerical column
weather[["precipitation", "temp_max", "temp_min"]].mean()

precipitation     3.029432
temp_max         16.439083
temp_min          8.234771
dtype: float64

In [78]:
# Compute the mean of each numerical column
weather[["precipitation", "temp_max", "temp_min"]].median()

precipitation     0.0
temp_max         15.6
temp_min          8.3
dtype: float64

In [79]:
# Compute the mean of each numerical column
weather[["precipitation", "temp_max", "temp_min"]].std()

precipitation    6.680194
temp_max         7.349758
temp_min         5.023004
dtype: float64

In [30]:
print(weather.min())
weather.max()

precipitation        0.0
temp_max            -1.6
temp_min            -7.1
wind                 0.4
weather          drizzle
month              April
dtype: object

precipitation         55.9
temp_max              35.6
temp_min              18.3
wind                   9.5
weather                sun
month            September
dtype: object

In [29]:
# get the unique values of a categorical column
weather.month.unique()

array(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype=object)

In [32]:
# Count the number of rows of each month
print(weather.month.value_counts())

# Count the number of rows of each weather category
print(weather.weather.value_counts())

month
January      124
March        124
May          124
July         124
August       124
October      124
December     124
April        120
June         120
September    120
November     120
February     113
Name: count, dtype: int64
weather
sun        714
fog        411
rain       259
drizzle     54
snow        23
Name: count, dtype: int64

## Sort the data

Sorting data allows you to arrange rows based on the values in one or more columns, making it easier to analyze.

You will learn how to:
1. sort the data frale by a single column
2. sort in descending order
3. sort by multiple columns
4. sort the index

In [102]:
weather[weather.month.isin(["December", "January", "February"])].reset_index(
)

,index,date,precipitation,temp_max,temp_min,wind,weather,month,temp_mean
0,0,2012-01-01,0.0,12.8,5.0,4.7,drizzle,January,8.90
1,1,2012-01-02,10.9,10.6,2.8,4.5,rain,January,6.70
2,2,2012-01-03,0.8,11.7,7.2,2.3,rain,January,9.45
3,3,2012-01-04,20.3,12.2,5.6,4.7,rain,January,8.90
4,4,2012-01-05,1.3,8.9,2.8,6.1,rain,January,5.85
...,...,...,...,...,...,...,...,...,...
356,1456,2015-12-27,8.6,4.4,1.7,2.9,fog,December,3.05
357,1457,2015-12-28,1.5,5.0,1.7,1.3,fog,December,3.35
358,1458,2015-12-29,0.0,7.2,0.6,2.6,fog,December,3.90
359,1459,2015-12-30,0.0,5.6,-1.0,3.4,sun,December,2.30
360,1460,2015-12-31,0.0,5.6,-2.1,3.5,sun,December,1.75

In [105]:
weather.sort_values("temp_max", ascending=False).head(10)

,date,precipitation,temp_max,temp_min,wind,weather,month,temp_mean
953,2014-08-11,0.5,35.6,17.8,2.6,rain,August,26.70
1295,2015-07-19,0.0,35.0,17.2,3.3,sun,July,26.10
228,2012-08-16,0.0,34.4,18.3,2.8,sun,August,26.35
912,2014-07-01,0.0,34.4,15.6,3.5,sun,July,25.00
1306,2015-07-30,0.0,34.4,17.2,3.5,sun,July,25.80
1307,2015-07-31,0.0,34.4,17.8,2.6,sun,July,26.10
217,2012-08-05,0.0,33.9,17.8,1.9,sun,August,25.85
216,2012-08-04,0.0,33.9,16.7,3.7,sun,August,25.30
619,2013-09-11,0.0,33.9,16.1,2.4,sun,September,25.00
1278,2015-07-02,0.0,33.9,17.8,3.4,sun,July,25.85

In [80]:
# Sorting a data frame by a single column

# Create a sample data frame
data = {"Name": ["Alice", "Bob", "Charlie", "David"],
        "Age": [25, 22, 30, 28],
        "Salary": [50000, 60000, 75000, 70000]}
df = pd.DataFrame(data)

# Sort by the "Age" column in ascending order
df_sorted_age = df.sort_values(by="Age")
print(df_sorted_age)

      Name  Age  Salary
1      Bob   22   60000
0    Alice   25   50000
3    David   28   70000
2  Charlie   30   75000

In [81]:
# Sorting in descending order

df_sorted_age_desc = df.sort_values(by="Age", ascending=False)
print(df_sorted_age_desc)

      Name  Age  Salary
2  Charlie   30   75000
3    David   28   70000
0    Alice   25   50000
1      Bob   22   60000

In [82]:
# Sorting by multiple columns

df_sorted_multiple = df.sort_values(by=["Age", "Salary"], ascending=[True, False])
print(df_sorted_multiple)

      Name  Age  Salary
1      Bob   22   60000
0    Alice   25   50000
3    David   28   70000
2  Charlie   30   75000

In [83]:
# Sorting the index, i.e. reorder the rows with respect to the row names

df_sorted_index = df.sort_index()
print(df_sorted_index)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   22   60000
2  Charlie   30   75000
3    David   28   70000

In [ ]:
# Exercise: apply the sorting methods on the weather dataset and the employees dataset

# TO DO